fish_dir_structure:
  - "~/.config/fish"
  - "~/.config/fish/completions"
  - "~/.config/fish/functions"
  - "~/.config/fish/conf.d"

fish_files:
  - ['my_aliases.fish','~/.config/fish/conf.d/my_aliases.fish']
  - ['config.fish','~/.config/fish/config.fish']

fish_shell: "/usr/bin/fish"
