- name: Make sure home local has a bin dir
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
  loop:
    - "/home/{{ ansible_user }}/.local/share/fonts"
    - "/home/{{ ansible_user }}/.local/bin"
    - "/home/{{ ansible_user }}/oh-my-posh"

- name: Install oh-my-posh on system
  ansible.builtin.shell:
    cmd: curl -s https://ohmyposh.dev/install.sh | bash -s -- -d ~/.local/bin
  register: ohmyposh_install

- name: Install font onto system
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ item.0 }}/{{ item.1 }}.zip
    dest: ~/.local/share/fonts/
    remote_src: yes
  loop: "{{ ohmyposh_fonts }}"

- name: Update font cache
  ansible.builtin.command:
    cmd: fc-cache -f -v
  register: fc_cache

- name: Grab latest theme
  ansible.builtin.get_url:
    src: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/refs/heads/main/themes/powerline.omp.json
    dest: "/home/{{ ansible_user }}/oh-my-posh/powerline.omp.json"
    user: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

